;;start package.el with emacs
(require 'package)

(require 'self-init-require-package)
(require 'self-init-common)
;; (require 'self-init-linum-mode)
(require 'self-init-company)
(require 'self-init-irony)
;; (require 'self-init-lsp-mode)
(require 'self-init-flycheck)
(require 'self-init-gtags)
(require 'self-init-ctags)
(require 'self-init-counsel-gtags)
(require 'self-init-clipboard)
(require 'self-init-cc-mode)
(require 'self-init-lua-mode)
(require 'self-init-python-mode)
(require 'self-init-cmake-mode)
(require 'self-init-protobuf-mode)
(require 'self-init-systemtap-mode)
(require 'self-init-nginx-mode)
(require 'self-init-go-mode)
(require 'self-init-editing-utils)


(provide 'init-local)
