(require-package 'google-c-style)
(require-package 'company-c-headers)
(require-package 'company-irony)
(require-package 'company-irony-c-headers)
(require-package 'company-lsp)
(require-package 'company-anaconda)
(require-package 'lsp-python)
(require-package 'cmake-mode)
(require-package 'counsel-gtags)
(require-package 'flycheck-irony)
(require-package 'ggtags)
(require-package 'irony)
(require-package 'lsp-mode)
(require-package 'lsp-ui)
(require-package 'company-lua)
(require-package 'zenburn-theme)


(provide 'wdq-init-require-package)
